version: "3"

services:
  web:
    build: .
    ports:
      - 8088:80
    command:
      [
        "flask",
        "run",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
      ]
    environment:
      - FLASK_ENV=development
      - CACHE_DIR=/cache
      - CLEAR_CACHE=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - cache:/cache
      - ./:/app
    restart: unless-stopped

  worker:
    build: .
    command:
      [
        "celery",
        "--app",
        "app.celery",
        "worker",
        "--pool",
        "eventlet",
        "--autoscale",
        "10,2",
        "--loglevel=info",
        "--concurrency=10"
      ]
    volumes:
      - .:/usr/src/app
      - cache:/cache
    environment:
      - CACHE_DIR=/cache
      - CLEAR_CACHE=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

volumes:
  cache:
