version: "3"

services:
  web:
    image: ghcr.io/zkhan93/epos:latest
    ports:
      - 80
    environment:
      - CACHE_DIR=/tmp/cache
      - CLEAR_CACHE=False
    volumes:
      - epos-cache:/tmp/cache
    # labels:
    #   - traefik.enable=${TRAEFIK_ENABLE:-true}
    #   - traefik.http.routers.khancave-epos.rule=Host(`${EPOS_DOMAIN}`)
    #   - traefik.http.routers.khancave-epos.tls.certresolver=le
    restart: unless-stopped

  worker:
    image: ghcr.io/zkhan93/epos:latest
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  redis:
    image: redis:7-alpine

volumes:
  epos-cache:
