version: "3"

services:
  epos:
    image: ghcr.io/zkhan93/epos:latest
    ports:
      - 80
    environment:
      - CACHE_DIR=/tmp/cache
    volumes:
      - epos-cache:/tmp/cache
    # labels:
    #   - traefik.enable=${TRAEFIK_ENABLE:-true}
    #   - traefik.http.routers.khancave-epos.rule=Host(`${EPOS_DOMAIN}`)
    #   - traefik.http.routers.khancave-epos.tls.certresolver=le
    restart: unless-stopped

volumes:
  epos-cache:
