version: "3"

services:
  web:
    image: ghcr.io/zkhan93/epos:latest
    ports:
      - 80
    environment:
      - CACHE_DIR=/cache
      - CLEAR_CACHE=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - epos-cache:/cache
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.khancave-epos.rule=Host(`${EPOS_DOMAIN}`)
      - traefik.http.routers.khancave-epos.tls.certresolver=le
    restart: unless-stopped

  worker:
    image: ghcr.io/zkhan93/epos:latest
    entrypoint:
      [
        "celery",
        "worker",
        "--app",
        "server.celery",
        "--pool",
        "eventlet",
        "--autoscale",
        "10,2",
        "--loglevel=info"
      ]
    volumes:
      - .:/usr/src/app
      - epos-cache:/cache
    environment:
      - CACHE_DIR=/cache
      - CLEAR_CACHE=False
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

    depends_on:
      - web
      - redis

  flower:
    image: ghcr.io/zkhan93/epos:latest
    entrypoint:
      [
        "celery",
        "--app",
        "server.celery",
        "flower",
        "--address=0.0.0.0",
        "--port=80",
        "--url_prefix=flower"
      ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.epos-flower.rule=Host(`${EPOS_DOMAIN}`) && PathPrefix(`/flower`)
      - traefik.http.routers.epos-flower.tls.certresolver=le

  redis:
    image: redis:7-alpine

volumes:
  epos-cache:
